#Author: Samuel Steinberg
#Date: March 7th, 2019
#CS420 - Project 4

CC = g++
CFLAGS = -g -Wall
VER = -std=c++11
TARGET = GenAlgorithm
all = $(TARGET)
$(TARGET): $(TARGET).cpp
	$(CC) $(CFLAGS) $(VER) -o $(TARGET) $(TARGET).cpp
clean:
	$(RM) $(TARGET)
